---
- hosts: openstack
  gather_facts: no
  become: no

  tasks:
    - include_role:
        name: image
      vars:
        action: prepare
        os: "{{ lookup('env', 'TEST_OS') }}"
      when:
        - image_format == "raw" or image_format == "vhd"

- hosts: esxi
  gather_facts: no
  become: no

  tasks:
    - include_role:
        name: image
      vars:
        action: build
        platform: esxi
        os: "{{ lookup('env', 'TEST_OS') }}"
      when:
        - image_format == "vmdk"
