---
- hosts: openstack
  gather_facts: no
  become: no

  tasks:
    - include_role:
        name: image
      vars:
        action: prepare
        target: openstack
        os: "{{ lookup('env', 'TEST_OS') }}"
      when:
        - cloud_platform == "aws" or cloud_platform == "azure" or cloud_platform == "openstack"
        - arch == "x86_64"

- hosts: beaker
  gather_facts: no
  become: no

  tasks:
    - include_role:
        name: image
      vars:
        action: prepare
        target: beaker
        os: "{{ lookup('env', 'TEST_OS') }}"
      when:
        - cloud_platform == "aws"
        - arch == "aarch64"

- hosts: builder

  tasks:
    - include_role:
        name: image
      vars:
        action: create
        target: qcow2
        os: "{{ lookup('env', 'TEST_OS') }}"
      when:
        - cloud_platform == "aws" or cloud_platform == "azure" or cloud_platform == "openstack"

- hosts: openstack
  gather_facts: no
  become: no

  tasks:
    - include_role:
        name: image
      vars:
        action: clean
        target: openstack
      when:
        - cloud_platform == "aws" or cloud_platform == "azure" or cloud_platform == "openstack"
        - arch == "x86_64"

- hosts: beaker
  gather_facts: no
  become: no

  tasks:
    - include_role:
        name: image
      vars:
        action: clean
        target: beaker
      when:
        - cloud_platform == "aws"
        - arch == "aarch64"

- hosts: aws
  gather_facts: yes
  become: no

  tasks:
    - include_role:
        name: image
      vars:
        action: upload
        target: "{{ cloud_platform }}"
        os: "{{ lookup('env', 'TEST_OS') }}"
      when:
        - cloud_platform == "aws"

- hosts: openstack
  gather_facts: yes
  become: no

  tasks:
    - include_role:
        name: image
      vars:
        action: upload
        target: "{{ cloud_platform }}"
        os: "{{ lookup('env', 'TEST_OS') }}"
      when:
        - cloud_platform == "openstack"

- hosts: esxi
  gather_facts: no
  become: no

  tasks:
    - include_role:
        name: image
      vars:
        action: build
        os: "{{ lookup('env', 'TEST_OS') }}"
      when:
        - cloud_platform == "esxi"
