---
- hosts: "{{ cloud_platform }}"
  gather_facts: no
  become: no
  vars:
    project: cki

  tasks:
    - include_role:
        name: kernel
      vars:
        action: download

    - include_role:
        name: guest
      vars:
        action: deploy

    - name: keep private key permission to 600
      file:
        path: "key/identity"
        mode: "0600"

- hosts: guest
  tasks:
    - include_role:
        name: kernel
      vars:
        action: install

    - include_role:
        name: test
      vars:
        run: ltp

- hosts: "{{ cloud_platform }}"
  gather_facts: no
  become: no
  vars:
    project: cki

  tasks:
    - name: get host info
      vmware_host_facts:
        hostname: "{{ vsphere_server }}"
        username: "{{ vsphere_username }}"
        password: "{{ vsphere_password }}"
        validate_certs: no
        esxi_hostname: "{{ esxi_host }}"
      register: host_facts

    - name: set cloud info varaible
      set_fact:
        cloud_info: "{{ host_facts.ansible_facts.ansible_distribution }}-{{ host_facts.ansible_facts.ansible_distribution_version }}"

    - include_role:
        name: umb
      vars:
        action: send

    - include_role:
        name: guest
      vars:
        action: remove
