---
- hosts: "{{ cloud_platform }}"
  gather_facts: no
  become: no
  vars:
    project: cki

  tasks:
    - include_role:
        name: kernel
      vars:
        action: download

    - include_role:
        name: guest
      vars:
        action: deploy

    - name: keep private key permission to 600
      file:
        path: "key/identity"
        mode: "0600"

- hosts: guest
  tasks:
    - include_role:
        name: kernel
      vars:
        action: install

    - include_role:
        name: test
      vars:
        run: ltp

- hosts: "{{ cloud_platform }}"
  gather_facts: no
  become: no
  vars:
    project: cki

  tasks:
    - include_role:
        name: guest
      vars:
        action: remove
