---
- hosts: "{{ cloud_platform }}"
  gather_facts: no
  become: no
  vars:
    project: cki

  tasks:
    - include_role:
        name: kernel
      vars:
        action: download
    - include_role:
        name: guest
      vars:
        action: deploy

- hosts: guest
  tasks:
    - include_role:
        name: kernel
      vars:
        action: install
