---
- hosts: "{{ cloud_platform }}"
  gather_facts: no
  become: no
  vars:
    project: kite

  tasks:
    - include_role:
        name: guest
      vars:
        action: deploy
        os: "{{ lookup('env', 'TEST_OS') }}"
