---
- name: remove openstack instance
  os_server:
    cloud: psi-openstack
    name: "{{ instance }}"
    state: absent
  ignore_errors: yes

- name: remove guest_ip from inventory file
  ini_file:
    path: "{{ playbook_dir }}/inventory"
    section: cloud:vars
    option: guest_ip
    state: absent
  ignore_errors: yes

- name: remove uuid from inventory file
  ini_file:
    path: "{{ playbook_dir }}/inventory"
    section: cloud:vars
    option: instance
    state: absent
  ignore_errors: yes
