---
- name: set kernel nvr
  set_fact:
    kernel_nvr: "{{ cki_repo_url.split('/raw/')[1].split('/')[-2] }}"

- name: set download url
  set_fact:
    cki_url: "{{ cki_repo_url.split('/raw/')[0] }}/download"

- name: show kernel_nvr value
  debug:
    var: kernel_nvr

- name: show cki_url value
  debug:
    var: cki_url

comment the following tasks for debugging
- name: download cki kernel artifacts
  get_url:
    url: "{{ cki_url }}"
    dest: "{{ playbook_dir }}"
    validate_certs: no

- name: create tmp folder to save unarchived file and folder
  file:
    path: "{{ playbook_dir }}/tmp"
    state: directory

- name: unzip cki artifacts
  unarchive:
    src: "{{ playbook_dir }}/artifacts.zip"
    dest: "{{ playbook_dir }}/tmp/"

- name: "copy kernel, core, and modules into {{ playbook_dir }}"
  copy:
    src: "{{ playbook_dir }}/tmp/artifacts/repo/{{ cki_nvr }}/{{ item }}"
    dest: "{{ playbook_dir }}/kernel/"
  with_items:
    - "kernel-{{ cki_nvr }}.rpm"
    - "kernel-core-{{ cki_nvr }}.rpm"
    - "kernel-modules-{{ cki_nvr }}.rpm"
    - "kernel-modules-extra-{{ cki_nvr }}.rpm"

- name: delete tmp folder
  file:
    path: "{{ playbook_dir }}/tmp"
    state: absent

- name: delete artifacts.zip
  file:
    path: "{{ playbook_dir }}/artifacts.zip"
    state: absent
