---
- name: terminate instance
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    instance_ids: "{{ ec2_instance.instance_ids[0] }}"
    state: absent
    wait: yes

- name: delete security group
  ec2_group:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    group_id: "{{ ec2_security_group.group_id }}"
    state: absent
