---
- name: terminate instance
  ec2:
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    instance_ids: "{{ ec2_instance.instance_ids[0] }}"
    state: absent
    wait: yes

- name: delete security group
  ec2_group:
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    group_id: "{{ ec2_security_group.group_id }}"
    state: absent
