---
- name: terminate instance
  ec2:
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    instance_ids: "{{ instance_id }}"
    state: absent
    wait: yes

- name: delete security group
  ec2_group:
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    group_id: "{{ group_id }}"
    state: absent
