---
- name: shut down guest
  vmware_guest_powerstate:
    hostname: "{{ vsphere_server }}"
    username: "{{ vsphere_username }}"
    password: "{{ vsphere_password }}"
    validate_certs: no
    name: "{{ esxi_guest_name }}"
    state: powered-off

- name: remove guest from disk
  vmware_guest:
    hostname: "{{ vsphere_server }}"
    username: "{{ vsphere_username }}"
    password: "{{ vsphere_password }}"
    validate_certs: no
    name: "{{ esxi_guest_name }}"
    state: absent
