---
- name: shut down guest
  vmware_guest_powerstate:
    hostname: "{{ vsphere_server }}"
    username: "{{ vsphere_username }}"
    password: "{{ vsphere_password }}"
    validate_certs: no
    uuid: "{{ uuid }}"
    state: powered-off
  ignore_errors: yes

- name: remove guest from disk
  vmware_guest:
    hostname: "{{ vsphere_server }}"
    username: "{{ vsphere_username }}"
    password: "{{ vsphere_password }}"
    validate_certs: no
    uuid: "{{ uuid }}"
    state: absent
  ignore_errors: yes

- name: remove guest_ip from inventory file
  ini_file:
    path: "{{ playbook_dir }}/inventory"
    section: cloud:vars
    option: guest_ip
    state: absent
  ignore_errors: yes

- name: remove uuid from inventory file
  ini_file:
    path: "{{ playbook_dir }}/inventory"
    section: cloud:vars
    option: uuid
    state: absent
  ignore_errors: yes
