---
- name: remove openstack instance
  os_server:
    cloud: psi-openstack
    name: "{{ instance_name }}"
    state: absent

- name: remove security group
  os_security_group:
    cloud: psi-openstack
    name: kite-image
    state: absent

- name: remove keypair
  os_keypair:
    cloud: psi-openstack
    name: kite-image-key
    state: absent
