---
- name: image building dependence
  dnf:
    name:
      - curl
      - expect
      - sed
      - tar
      - qemu-kvm
      - virt-install
      - libvirt-daemon-kvm
    state: latest
  become: yes

- name: generate kickstart file
  template:
    src: ks-cfg.j2
    dest: "/home/fedora/{{ os }}.ks"

- name: copy virt-install script
  copy:
    src: virt-install-image
    dest: "/home/fedora/virt-install-image"
    mode: '0764'

- name: build qcow2 image first
  command: /home/fedora/virt-install-image /home/fedora/{{ os }}.qcow2 {{ os }}.ks {{ repos[os]["baseos"] }}

- name: "convert qcow2 to {{ image_type[cloud_platform] }}"
  command: qemu-img convert -O {{ image_type[cloud_platform] }} /home/fedora/{{ os }}.qcow2 /home/fedora/{{ os }}.{{ image_type[cloud_platform] }}
  when: cloud_platform == "azure"

- name: fetch image back
  fetch:
    src: "/home/fedora/{{ os }}.{{ image_type[cloud_platform] }}"
    dest: "{{ playbook_dir }}/"
    validate_checksum: yes
    flat: yes
