---
- name: get test result
  set_fact:
    test_result: "{{ lookup('file', 'ltp.result') }}"

- name: set vault password file
  copy:
    content: "{{ lookup('env', 'VSPHERE_PASSWORD') }}"
    dest: "~/.config/ansible-vault"

- name: they become real
  command: ansible-vault decrypt -v --vault-password-file ~/.config/ansible-vault {{ role_path }}/files/{{ item }} --output umb-{{ item }}.{{ item.split('-')[1] }}
  loop:
    - sending-crt
    - sending-key

- name: send result back
  command: "{{ role_path }}/files/cki-send.py --broker={{ broker_ip }} --port={{ stomp_port }} --ssl_cert_file={{ ssl_cert_file }} --ssl_key_file={{ ssl_key_file }} --pipeline_id={{ pipeline_id }} --arch=x86_64 --log_url={{ log_url }} --result={{ test_result }} --cloud={{ cloud_info }}"
