---
name: RHEL 8.3 OpenStack image

on:
  schedule:
    # At 8:25 every Sunday
    - cron: '25 8 * * 0'

jobs:
  aws_ec2_ami:
    name: build rhel 8.3 openstack image
    runs-on: kite-runner

    steps:
      - name: Checkout kite-deploy repository
        uses: actions/checkout@v2

      - name: Build AMI
        run: ansible-playbook -v -i inventory -e cloud_platform=openstack build.yaml

      - name: Remove runner
        if: ${{ always() }}
        run: |
          RUNNER_NAME=$(cat /etc/hostname)
          curl -X PUT $KITE_CONTROLLER_API_NETLOC/runner/delete/$RUNNER_NAME > /dev/null 2>&1 &
